<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
use Laminas\Json\Json;
?>
<div class="accordion" id="accordion<?php echo $current; ?>">
	<?php
    $current = 0;
    foreach ($this->__vars as $name => $var) :
        $previous = $current - 1;
        $next = $current + 1;
    ?>
	<div class="accordion-item">
		<h2 class="accordion-header" id="heading<?php echo $current; ?>">
			<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<?php echo $current; ?>" aria-expanded="true" aria-controls="collapse<?php echo $current; ?>">
				<span style="white-space: nowrap"><?php echo $name;?></span>
			</button>
		</h2>
		<div id="collapse<?php echo $current; ?>" class="accordion-collapse collapse" aria-labelledby="heading<?php echo $current; ?>" data-bs-parent="#accordion<?php echo $current; ?>">
			<div class="accordion-body">
				<?php 
// 				echo "<HR><a id='$current'></a>\n<a href='#$next'>[Next]</a> <a href='#$previous'>[Previous]</a> <h1>$name</h1>\n";
				echo "<pre>" . Json::prettyPrint($var, array('indent' => '    ')) . "</pre>";
				$current++;
				?>
                    
			</div>
		</div>
	</div>
	<?php 
    endforeach;
	?>
</div>