<div class="row">
	<div class="col">
		<div class="card mb-4">
			<div class="card-header d-flex justify-content-between">
        		<div>
        			<b>Upload Tax Documents</b>
        		</div>
        	</div>
        	<div class="card-body">
        		<?php 
        		$this->form->prepare();
        		$this->form->setAttribute('action', $this->url('application/files', ['action' => 'upload']));
        		echo $this->form()->openTag($this->form); 
        		echo $this->formCollection($this->form);
        		echo $this->form()->closeTag($this->form);
        		?>
        	</div>
    	</div>
	</div>
</div>