<style type="text/css">
.fa-money-check     { colo: Blue; }
.fa-cc-paypal       { colo: Orange; }
.fa-money-bill-wave { colo: Green; }
</style>

<div class="jumbotron">
    <h1 class="display-4"><b>Middlesex United Way</b></h1>
    <figure>
    	<blockquote class="blockquote">
    		<p>Now more than ever, city government and community nonprofits are depending on each other to help our constituents during these incredibly challenging times. We are lucky in Middletown to have such wonderful partners in the Middlesex United Way, which has stepped up again and again during the COVID-19 pandemic to support our most vulnerable residents. Supporting United Way means supporting local nonprofits all throughout Middletown - keeping your charitable dollars right here at home, where they go the furthest and matter the most. I want to thank Cathy Lechowicz for her leadership of the City of Middletown's giving campaign, and encourage everyone to give what they are able to support our local nonprofits through the Middlesex United Way.</p>
    	</blockquote>
    	<figcaption class="blockquote-footer">Mayor Ben Florsheim</figcaption> 
    </figure>
</div>

<div class="row row-cols-1 row-cols-md-3">
	<div class="col">
        <div class="card">
            <h2 class="card-header">Payroll Deduction</h2>
            <div class="card-body">
                <p>
                    If you want to donate by payroll deduction, select the amount you want deducted weekly.
                </p>
                <i class="fas fa-9x fa-money-check"></i>
                
            </div>
            <div class="card-footer">
            	<a class="btn btn-primary" href="<?php echo $this->url('application/unitedway', ['action' => 'payroll', 'uuid' => $this->uuid]); ?>">Payroll Deduction &raquo;</a>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <h2 class="card-header">One Time - Credit</h2>
            <div class="card-body">
                <p>
                    If you want to donate by credit card, you will be re-directed to a PayPal page which is administered by the Middlesex United Way.
                </p>
                <i class="fab fa-9x fa-cc-paypal"></i>
            </div>
            <div class="card-footer">
            	<a class="btn btn-primary" target="_blank" href="https://unitedway.formstack.com/forms/city_of_middletown_2021_2022">PayPal / Credit Card &raquo;</a>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <h2 class="card-header">One Time - Cash</h2>
            <div class="card-body">
                <p>
                    If you want to donate by cash or check, please use an interoffice envelope and send to Cathy Lechowicz (Recreation and Senior Services).
                </p>
                <i class="fas fa-9x fa-money-bill-wave"></i>
            </div>
            <div class="card-footer">
            	<a class="btn btn-primary" href="<?php echo $this->url('application/unitedway', ['action' => 'cash', 'uuid' => $this->uuid]); ?>">Cash / Check &raquo;</a>
            </div>
        </div>
    </div>
</div>