<?php
$form->prepare();
$form->setAttribute('action', $this->url('box', ['action' => 'update_warrant']));
?>
<div class="row">
	<div class="col">
		<div class="card mb-4">
			<div class="card-header d-flex justify-content-between">
        		<div>
        			<b>Enter Warrant Number</b>
        		</div>
        	</div>
        	<div class="card-body">
        		<?php 
        		echo $this->form()->openTag($form);
        		echo $this->formCollection($form);
        		echo $this->form()->closeTag($form);
        		?>
        	</div>
		</div>
	</div>
	<div class="col">
		<div class="card mb-4">
			<div class="card-header d-flex justify-content-between">
        		<div>
        			<b>Warrant Information</b>
        		</div>
        	</div>
        	<div class="card-body">
        		<pre>
        		<?php 
        		print_r($warrant->getArrayCopy());
        		?>
        		</pre>
        	</div>
		</div>
	</div>
</div>
<?php if (isset($folders)) : ?>
<div class="row">
<div class="col">
		<div class="card mb-4">
			<div class="card-header d-flex justify-content-between">
        		<div>
        			<b>Folder Information</b>
        		</div>
        	</div>
        	<div class="card-body">
        		<pre>
        		<?php 
        		?>
        		</pre>
        	</div>
		</div>
	</div>
	<div class="col">
		<div class="card mb-4">
			<div class="card-header d-flex justify-content-between">
        		<div>
        			<b>Box Information</b>
        		</div>
        	</div>
        	<div class="card-body">
        		<pre>
Folders Found: <?php echo $folders->total_count . "\n"; ?>
Search Results:
	Files: <?php echo $search_results->total_count . "\n"; ?>
	Limit: <?php echo $search_results->limit . "\n"; ?>
	Files with Metadata: <?php echo $with . "\n"; ?>
	Files without Metadata: <?php echo $without . "\n"; ?>
        		</pre>
        	</div>
		</div>
	</div>
</div>
<?php endif; ?>