<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="p-3 mb-3 bg-light rounded-3">
	<div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">What's New</h1>
    
        <ul>
        	<li>Paperless Paystubs.  Employees are now able to view paystubs electronically.
        	<li>Registration.  Employees without MIDNET accounts can request access to Chronos.
        </ul>
    
        <hr class="my-4">
    
    </div>
</div>

<div class="row">
	<div class="col-lg mb-3">
        <div class="card">
            <h2 class="card-header">Step 1: Login</h2>
            <div class="card-body">
                <p>
                    Log into the application using the same credentials (username and password) you log into your workstation with.
                </p>
            </div>
            <div class="card-footer">
            	<a class="btn btn-primary" href="<?php echo $this->url('user/login'); ?>">Login &raquo;</a>
            	<a class="btn btn-primary" href="<?php echo $this->url('user/default', ['action' => 'register']); ?>">Register &raquo;</a>
            </div>
        </div>
    </div>

	<div class="col-lg mb-3">
        <div class="card">
            <h2 class="card-header">Step 2: Enter Time</h2>
            <div class="card-body">
                <p>
                    Enter your time in the daily timesheet form.  Add additional pay codes using the tools at the bottom of the form.
                </p>
            </div>
            <div class="card-footer">
            	<a class="btn btn-primary" href="<?php echo $this->url('timecard/timesheet'); ?>">Timesheet &raquo;</a>
            </div>
        </div>
    </div>

	<div class="col-lg mb-3">
        <div class="card">
            <h2 class="card-header">Help &amp; Support</h2>
            <div class="card-body">
                <p>
                    If you are having trouble submitting your timecard, please submit a Help Desk Ticket by following the link below.
                </p>
            </div>
            <div class="card-footer">
            	<a class="btn btn-primary" href="https://kbox.middletownct.gov/" target="_blank">Submit Ticket &raquo;</a>
            	<a class="btn btn-primary" href="https://connect.middletownct.gov/" target="_blank">Remote Support &raquo;</a>
            </div>
        </div>
    </div>
</div>
