<style type="text/css" media="print">
    @media print{
        @page { size: landscape; }
    }
    body { 
        zoom: 65%; 
    }
</style>

<?php
global $report_data;
global $employees;
global $work_week;

$accruals = [
    'S',
    'V',
    'P',
    'C',
    'F',
    '0',
    'M',
    'UN',
    'J',
    'CT',
    'TD',
    'L',
    'LD',
    'OTH',
    'CV',
    'CCV',
];

$dow = ['SUN','MON','TUE','WED','THU','FRI','SAT'];

foreach ($this->data as $record) {
    if (!isset($work_week)) {
        $work_week = $record['WORK_WEEK'];
    }
    
    $index = sprintf('%s-%s-%s', $record['TIME_SUBGROUP'], $record['EMP_NUM'], $record['CODE']);
    
    $report_data[$index] = [
        'RECORD' => $record,
    ];
}


ksort($report_data);
$current_employee = 0;
$total = 0;
?>

<h1>Middletown Police Department -- Payroll Information</h1>
<h3>Totals for Week Ending: <?=$work_week?></h3>


<?php foreach ($report_data as $employee) : ?>
<div class="container-fluid border">
<?php if ($current_employee != $employee['RECORD']['EMP_NUM']) : ?>
<?php $current_employee = $employee['RECORD']['EMP_NUM']; ?>
<?php $total = 0; ?>
	<div class="row mt-4">
		<div class="col"><?=$employee['RECORD']['LNAME']?>, <?=$employee['RECORD']['FNAME']?> [<?=$employee['RECORD']['EMP_NUM']?>]</div>
	</div>
	<div class="row">
		<?php foreach ($accruals as $code) : ?>
		<div class="col">(<?=$code?>)</div>
		<?php endforeach; ?>
	</div>
	<div class="row">
		<?php foreach ($accruals as $code) : ?>
		<div class="col border"><span class="badge bg-secondary text-light" id="<?=sprintf('%s-%sP',$current_employee,$code);?>"></span></div>
		<?php endforeach; ?>
	</div>
	
	<!-- Daily Header Row -->
	<div class="row">
		<?php for ($i=0; $i < 5; $i++) : ?>
		<div class="col-2">
			<div class="row">
				<div class="col">Day</div>
        		<div class="col">Hrs</div>
        		<div class="col">Stat</div>
        		<div class="col">Note</div>
			</div>
		</div>
		<?php endfor; ?>
	</div>

<?php endif; ?>
	<div class="row">
		<?php $padding = 5; ?>
		<?php foreach ($dow as $day) : ?>
			<?php if (!empty($employee['RECORD'][$day])) : ?>
			<?php $padding--; ?>
			<div class="col-2">
				<div class="row">
            		<div class="col"><?=$day?></div>
            		<div class="col"><?=$employee['RECORD'][$day]?></div>
            			<?php $total += $employee['RECORD'][$day]; ?>
            		<div class="col"><?=$employee['RECORD']['CODE']?></div>
            		<div class="col"></div>
        		</div>
    		</div>
			<?php endif; ?>
    		
		<?php endforeach; ?>
		<?php for ($j=0; $j < $padding; $j++) : ?>
		<div class="col-2"></div>
		<?php endfor; ?>
		
		<div class="col-2">
			<div class="row">
				<div class="col"><?=$employee['RECORD']['CODE']?></div>
				<div class="col"><?=$total;?></div>
				
				<script type="text/javascript">
					document.getElementById("<?=sprintf('%s-%s',$current_employee,$employee['RECORD']['CODE']);?>").innerHTML = "<?=$total?>";
				</script>
			</div>
		</div>
		<?php $total = 0; ?>
	</div>
</div>
<?php endforeach; ?>
